/*
	Chooply 2011
	List of englist stopwords
*/


stopWords = {
	//javascript and css words
	'cookie': true,
	'this': true,
	'math': true,
	'location': true,
	'http': true,
	'https': true,
	'www': true,
	'com': true,
	'path': true,
	'undefined': true,
	'type': true,
	'false': true,
	'document': true,
	'function': true,
	'typeof': true,
	'width': true,
	'height': true,
	'font': true,
	'text': true,
	'write': true,
	'request': true,
	'javascript': true,
	'left': true,
	'right': true,
	'null': true,
	'from': true,
	'var': true,
	'useragent': true,
	'indexof': true,
	'href': true,
	'target': true,
	'border': true,
	'script': true,
	'style': true,
	'init': true,
	'html': true,
	'doubleclick': true,
	'none': true,
	'position': true,
	'display': true,
	'getelementbyid': true,
	'array': true,
	'block': true,
	'parent': true,
	'absolute': true,
	
	
	//site words
	'login': true,
	'logout': true,
	'menu': true,
	'reply': true,
	'more': true,
	'continue': true,
	'comment': true,
	'comments': true,
	'time': true,
	'charset': true,
	'escape': true,
	'context': true,
	'loadlikebutton':true,
	'page': true,
	'edit': true,
	'read': true,
	'free': true,
	'categories': true,
	'article': true,
	'articles': true,
	'notes': true,
	'sign': true,
	
	
	//english words
	'when': true,
	'about': true,
	'the': true,
	'their': true,
	'there': true,
	'they': true,
	'them': true,
	'that': true,
	'than': true,
	'these': true,
	'and': true,
	'what': true,
	'where': true,
	'your': true,
	'with': true,
	'into': true,
	'after': true,
	'can': true,
	'could': true,
	'have': true,
	'many': true,
	'says': true,
	'some': true,
	'where': true,
	'over': true,
	'maybe': true,
	'later': true,
	'thanks': true,
	'while': true
};
